apps/comments/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('',
    url(r'comments/new/$', 'comments.views.comments_add', name='comments_add'),
)

urls.py
# Uncomment the next two lines to enable the admin:
from articles.views import ArticleList, ArticleView
from company.views import counter, RegisterView, CompanyView, CompanyList, \
    AddRespond, FrontView, StatView, TenderAdd, \
    RespondList, OfferView, EditProfile, Avatar, \
    OrdersSend, CompanyScript, DeliveryZonePriceView, \
    CompetitionView, CompetitionDetailView, \
    CompetitionListView
from company.ajax import poll_post, vote
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.views.generic.base import RedirectView
from cms.sitemaps import CMSSitemap

from news.views import NewsList, NewsView, AddComment
from apps.comments.views import AddLike

from awards.views import FrontAwards, VoteAwards, AddVote,\
                         RequestForm, SuccessRequest
import settings

from adminplus.sites import AdminSitePlus
from django.conf.urls.defaults import patterns, include, url
from sitemap import CompanyObjects


sitemaps = {
    'objects': CompanyObjects,
}
admin.site = AdminSitePlus()
admin.autodiscover()


urlpatterns = patterns('',
    (r'^ckeditor/', include('ckeditor.urls')),
    (r'^admin/', include(admin.site.urls)),

    url(r'^order/', include('order.urls', 'order')),
    url(r'^', include('company.urls')),
    url(r'^awards/$', FrontAwards.as_view(), name='awards'),
    url(r'^awards/vote/(?P<type>[0-9A-Za-z-_.//]+)/$', VoteAwards.as_view(), name='awards_vote'),
    url(r'^awards/request/$', RequestForm.as_view(), name='awards_request'),
    url(r'^awards/request/success/$', SuccessRequest.as_view(), name='awards_success'),
    url(r'^awards/add/vote/$', AddVote.as_view(), name='awards_add_vote'),
    url(r'^tender/$', TenderAdd.as_view(), name='tender'),

    url(r'^like/add/(?P<pk>\d+)/$', AddLike.as_view(), name="add_like"),
    url(r'^news/$', NewsList.as_view(), name='news_list'),
    url(r'^news/comment/$', AddComment.as_view(), name='add_comment'),
    url(r'^news/(?P<pk>[0-9A-Za-z-_.//]+)/$', NewsView.as_view(), name='news'),
    url(r'^articles/$', ArticleList.as_view(), name='article_list'),
    url(r'^articles/(?P<pk>[0-9A-Za-z-_.//]+)/$', ArticleView.as_view(), name='article'),
    # url(r'^category/(?P<pk>[0-9A-Za-z-_.//]+)/', CategoryView.as_view(template_name='category.html')),
    # url('^api/buy/product/$', CartAddItemView.as_view(action='post'), name='add_to_cart' ),
    # url(r'^shop/cart/$', CartView.as_view(), name='cart'),
    # url(r'^shop/checkout/$', CheckoutView.as_view(template_name='checkout.html'), name='checkout_selection'),

    # (r'^shop/', include(shop_urls)),
    (r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}),
# (r'^accounts/logout/$', RedirectView.as_view(url='/')),
    url(r'^accounts/', include('registration.urls')),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^robots.txt', include('robots.urls')),
    url(r'^chaining/', include('smart_selects.urls')),
    url(r'', include('comments.urls')),
    url(r'^landging/', include('cms_page.urls')),
    (r'^sitemap.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
    # (r'^sitemap/$', 'django.contrib.sitemaps.views.sitemap', {
    #     'sitemaps': {'cmspages': CMSSitemap},
    #     'mimetype': 'text/html',
    #     'template_name': 'inclusion/site_map.html'
    #     }),
    url(r'^', include('cms.urls')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/news/models.py
# vim:fileencoding=utf-8
from django.db.models import permalink
import os
import uuid
import settings
from sorl.thumbnail.fields import ImageField
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.


def get_file_path(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s.%s" % (uuid.uuid4(), ext)
    return os.path.join(getattr(settings, 'PRODUCT_IMAGE_UPLOAD_TO', 'news/'), filename)


class News(models.Model):
    class Meta(object):
        verbose_name = u'Новость'
        verbose_name_plural = u'Новости'
        ordering = ['-date']

    title = models.CharField(max_length=255, verbose_name=u'Заголовок')
    date = models.DateTimeField(max_length=255, verbose_name=u'Дата публикации')
    image = ImageField(verbose_name=u'Изображение', upload_to=get_file_path, null=True, blank=True)
    teaser = models.TextField(verbose_name=u'Анонс', blank=True, null=True)
    content = RichTextField(verbose_name=u'Текст')
    category = models.ManyToManyField('Category', verbose_name=u'Категории новости',blank=True, null=True)
    keywords = models.TextField(verbose_name=u'Мета Keywords', blank=True, null=True)
    description = models.TextField(verbose_name=u'Meta Description', blank=True, null=True)
    seo_title = models.CharField(max_length=255, verbose_name=u'Seo тайтл', blank=True, null=True,)
    comments_count = models.PositiveIntegerField(u'Количество комментариев', default=0)

    def __unicode__(self):
        return self.title

    @permalink
    def get_absolute_url(self):
        return 'news', (self.id, ), {}


class Category(models.Model):
    class Meta(object):
        verbose_name = u'Категория'
        verbose_name_plural = u'Категории'
        ordering = ['name']

    name = models.CharField(max_length=255, verbose_name=u'Название')

    def __unicode__(self):
        return self.name


class Comment(models.Model):
    class Meta(object):
        verbose_name = u'Комментарий'
        verbose_name_plural = u'Комментарии'
        ordering = ['-created']

    news = models.ForeignKey(News, verbose_name=u'Новость', related_name='comments')
    created = models.DateTimeField(auto_now_add=True, verbose_name=u'Дата', null=True, blank=True)
    name = models.CharField(max_length=255, verbose_name=u'Имя')
    email = models.EmailField(max_length=255, verbose_name=u'E-mail')
    text = RichTextField(verbose_name=u'Текст отзыва', config_name='respond', max_length=2500)
    moderate = models.BooleanField(verbose_name=u'Модерация', default=False)

    def __unicode__(self):
        return "%s - %s" % (self.name, self.email)

templates/inclusion/alert.html
<div id="success_rate" class="modal">
    <div class="success_rate">
        <p>Ваша ставка успешно размещена</p>
        <div class="link-block clearfix">
            <a href="" class="one-more">Сделать еще одну ставку </a>
            <a href="" class="back">Перейти на страницу заказа</a>
        </div>
    </div>
</div>

templates/inclusion/can_reg.html
<div class="container-sm">
    <form action="{% url registration_choice %}">
        <button class="btn reg-btn" type="submit">Зарегистрироваться</button>
    </form>
    <p>Вы перевозчик или курьерская служба?</p>
    <span>Зарегистрируйтесь и получайте уведомление о заказах</span>
</div>

templates/inclusion/change_profile.html
{% load widget_tweaks %}
<div class="function-block edit_profile">
    <a class="blue-btn click" href="#" id="edit_profile">Редактировать</a>
    <p>Для изменения своих данных нажмите на кнопку “Редактировать”</p>
</div>
<div class="function-block edit_profile hide">
    <a class="green-btn save" href="#" onclick="$('#form_profile').submit(); return false;">Сохранить</a>
    <a class="red-btn cancel click" href="">Отменить</a>
</div>
<div class="change_password">
    {% include 'inclusion/form_password_reset.html' %}
</div>
<div class="function-block edit_password">
    <a class="blue-btn lock change_password_b" href="#">сменить пароль</a>
    <p>Для смены пароля входа на сайт нажмите на кнопку “Сменить пароль”</p>
</div>
<div class="function-block edit_password hide">
    <a class="green-btn save" href="#" id="change_pass_submit">Сохранить</a>
    <a class="red-btn cancel change_password_b" href="">Отменить</a>
</div>
{#            <div class="change_password">#}
{#                <form class="change_password_form" action="{% url order:reset_password %}">#}
{#                    {% csrf_token %}#}
{#                    {{ field.label_tag }}#}
{#                    {{ field }}#}
{#                    {% if field.errors %}#}
{#                        {{ field.errors|striptags }}#}
{#                    {% endif %}#}
{#                    <a href="#lock" class=""> Подтвердить</a>#}
{#                    <a href="#lock">Отменить</a>#}
{#                </form>#}
{#            </div>#}

templates/inclusion/form_password_reset.html
{% load widget_tweaks %}
{% load company %}

<form class="change_password_form" action="{% url reset_password %}">
    {% csrf_token %}
    <em class="{{ password_form.password_cur|error }}">{{ password_form.password_cur.errors }}</em>
    {% render_field password_form.password_cur placeholder="Старый пароль" %}
    <em class="{{ password_form.password1|error }}">{{ password_form.password1.errors }}</em>
    {% render_field password_form.password1 placeholder="Новый пароль" %}
    <em class="{{ password_form.password2|error }}">{{ password_form.password2.errors }}</em>
    {% render_field password_form.password2 placeholder="Новый пароль еще раз" %}
</form>

templates/inclusion/head.html
<div class="header header-cp">
    <div class="container-sm">
        <a class="cp" href="#" title="">личный кабинет</a><span>|</span>
        <a class="exit-cp" href="{% url auth_logout %}" title="">выход</a><span>|</span>
        <p>{% firstof user.first_name user.username %}</p>
        {% if count_new_bet %}<a href="#" title=""><i>{{ count_new_bet }}</i></a>{% endif %}
    </div>
    <div class="container-lg">
        <h1>Личный кабинет, <span>{% firstof user.first_name user.username %}</span></h1>
    </div>
</div>

templates/inclusion/order_category.html
<div id="order_modal">
    <h3>Выберите категорию груза:</h3>
    <div class="order_modal_links clearfix">
        {% for category in category_list %}
            <a href="{% url order:order_form  category.pk %}" onclick="yaCounter16082527.reachGoal('FORMCLICK'); return true;">
                <img src="{{ category.icon.url }}" alt=""/>
                <span>{{ category.name }}</span>
            </a>
        {% endfor %}
    </div>
</div>

templates/inclusion/pagination.html
{% load encode_parameters %}
{% load static %}
{% load order_tags %}

{% if paginator.page_range|length > 1 %}
    <ul class="pagination">
        {% if page_obj.has_previous %}
            <li>
                <a href="{% get_params page=page_obj.previous_page_number %}#respondes">
                    <img src="{% static "new_img/left_arrow_icon.png" %}" alt="">
                </a>
            </li>
        {% endif %}
        {% if show_first %}
            <li><a href="{% get_params page=1 %}">1</a></li>
            <li><a href="javascript:void(0)">...</a></li>
        {% endif %}
        {% for num in range %}
            <li><a {% if page_obj.number == num %}class="current"{% endif %} href="{% get_params page=num %}#respondes">{{ num }}</a></li>
        {% endfor %}
        {% if show_last %}
            <li><a href="javascript:void(0)">...</a></li>
            <li><a href="{% get_params page=last_page %}#respondes">{{ last_page }}</a></li>
        {% endif %}
        {% if page_obj.has_next %}
            <li>
                <a href="{% get_params page=page_obj.next_page_number %}#respondes">
                    <img src="{% static 'new_img/right_arrow_icon.png' %}" alt="">
                </a>
            </li>
        {% endif %}
    </ul>
{% endif %}
{##}
{#{% if paginator.page_range|length > 1 %}#}
{#    <ul class="pagination">#}
{#        {% if page_obj.has_previos %}#}
{#            <li>#}
{#                <a href="?{{ request.GET|encode_parameters:page_obj.previos_page_number }}" class="prev">#}
{#                        <span>#}
{#                            <img src="{% static "new_img/left_arrow_icon.png" %}" alt="">#}
{#                        </span>#}
{#                </a>#}
{#            </li>#}
{#        {% endif %}#}
{#        {% for num in paginator.page_range %}#}
{#            <li><a {% if page_obj.number == num %}class="current"{% endif %} href="?{{ request.GET|encode_parameters:num }}">{{ num }}</a></li>#}
{#        {% endfor %}#}
{#        {% if page_obj.has_next %}#}
{#            <li class="next">#}
{#                <a href="?{{ request.GET|encode_parameters:page_obj.next_page_number }}">#}
{#                <span>#}
{#                    <img src="{% static "new_img/right_arrow_icon.png" %}" alt="">#}
{#                </span>#}
{#                </a>#}
{#            </li>#}
{#        {% endif %}#}
{#    </ul>#}
{#{% endif %}#}

templates/inclusion/paginator.html
{% load static %}
{% load thumbnail %}
{% load company %}
{% load order_tags %}
{% load encode_parameters %}

{% if paginator.page_range|length > 1 %}
    <div class="new_pagination">
        {% if page_obj.has_previous %}
            <a href="{% get_params page=page_obj.previous_page_number %}#respondes">
                <img src="{% static 'new_img/left_icon.png' %}" alt="">
            </a>
        {% endif %}
        {% if show_first %}
            <a href="{% get_params page=1 %}#respondes">1</a>
            ...
        {% endif %}
        {% for num in range %}
            <a {% if page_obj.number == num %}class="active"{% endif %} title="" href="{% get_params page=num %}#respondes">{{ num }}</a>
        {% endfor %}
        {% if show_last %}
            ...
            <a href="{% get_params page=last_page %}#respondes">{{ last_page }}</a>
        {% endif %}
         {% if page_obj.has_next %}
            <a href="{% get_params page=page_obj.next_page_number %}#respondes">
                <img src="{% static 'new_img/right_icon.png' %}" alt="">
            </a>
        {% endif %}
    </div>
{% endif %}

templates/inclusion/respond.html
{% load static %}
{% load thumbnail %}
{% load company %}
{% load encode_parameters %}
{% load cms_tags sekizai_tags %}
{% load mptt_tags %}

{% for respond in list %}
    <div class="arrow_box">
        <div class="ellipse-box">
            <div class="ellipse {{ respond.mark|switch_class }}"></div>
        </div>
        <h5>Отзыв о перевозчике: <a href="{{ respond.company.get_absolute_url }}">«{% firstof respond.company.name respond.company.h1 %}»</a></h5>
        <p>{{ respond.text|safe|striptags }}</p>
        <div class="comm-info">
            <span class="name">{{ respond.name }}</span>
            <span class="date">{{ respond.created|date:"d M Y" }}</span>
            {% if respond.order %}<span class="bill">Накладная № {{ respond.order }}</span>{% endif %}
            {% if request.user.is_active %}
                <span class="answer"><a href="#" class='add_respond' data-company='{{ respond.company.id }}' rel="{{ respond.id }}" title="">Ответить</a></span>
            {% endif %}
        </div>
    </div>

    {% recursetree respond.get_descendants %}

        {% if node.moderate %}
            <div class="arrow_box children">
                <div class="ellipse-box">
                    <div class="ellipse {{ node.mark|switch_class }}"></div>
                </div>
                <h5>Отзыв о перевозчике: <a href="{{ node.company.get_absolute_url }}">«{% firstof node.company.name company.name node.company.h1  %}»</a></h5>
                <p>{{ node.text|safe|striptags }}</p>
                <div class="comm-info">
                    <span class="name">{{ node.name }}</span>
                    <span class="date">{{ node.created|date:"d M Y" }}</span>
                    {% if node.order %}<span class="bill">Накладная № {{ node.order }}</span>{% endif %}
                    {% if request.user.is_active %}
                        <span class="answer"><a href="#" class='add_respond' data-company='{{ node.company.id }}' rel="{{ node.id }}" title="">Ответить</a></span>
                    {% endif %}
                </div>
            </div>
            {% if not node.is_leaf_node %}
                <div class="children">
                    {{ children }}
                </div>
            {% endif %}
        {% endif %}

    {% endrecursetree %}

{% endfor %}
{% paginator %}

templates/inclusion/site_map.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% load company %}
{% load widget_tweaks %}

{% block title %}Карта сайта{% endblock %}
{% block title_content %}Карта сайта{% endblock %}

{% block right_content %}
    <h2>Карта сайта</h2>
    <div class="sitemap">
        {% spaceless %}
            <ul class="sitemap">
                {% for url in urlset %}
                    <a href="{{ url.get_absolute_url }}">{{ url.get_page_title }}</a>
                    <li>
                        {% if 'news' in url.get_absolute_url %}
                            <ul>
                                {% for obj in news %}
                                    <li><a href="{{ obj.get_absolute_url }}">{{ obj }}</a></li>
                                {% endfor %}
                            </ul>
                        {% elif 'rating/all' in url.get_absolute_url %}
                            <ul>
                                {% for obj in company %}
                                    <li><a href="{{ obj.get_absolute_url }}">{{ obj }}</a></li>
                                {% endfor %}
                            </ul>
                        {% elif 'articles' in url.get_absolute_url %}
                            <ul>
                                {% for obj in articles %}
                                    <li><a href="{{ obj.get_absolute_url }}">{{ obj }}</a></li>
                                {% endfor %}
                            </ul>
                        {% endif %}
                    </li>
                {% endfor %}
                {% for obj in pages %}
                    <li>
                        <a href="{{ obj.get_absolute_url }}">{{ obj }}</a>
                    </li>
                {% endfor %}
            </ul>
        {% endspaceless %}
    </div>
{% endblock %}