apps/comments/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('',
    url(r'comments/new/$', 'comments.views.comments_add', name='comments_add'),
)

urls.py
# Uncomment the next two lines to enable the admin:
from articles.views import ArticleList, ArticleView
from company.views import counter, RegisterView, CompanyView, CompanyList, \
    AddRespond, FrontView, StatView, TenderAdd, \
    RespondList, OfferView, EditProfile, Avatar, \
    OrdersSend, CompanyScript, DeliveryZonePriceView, \
    CompetitionView, CompetitionDetailView, \
    CompetitionListView
from company.ajax import poll_post, vote
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.views.generic.base import RedirectView
from cms.sitemaps import CMSSitemap

from news.views import NewsList, NewsView, AddComment
from apps.comments.views import AddLike

from awards.views import FrontAwards, VoteAwards, AddVote,\
                         RequestForm, SuccessRequest
import settings

from adminplus.sites import AdminSitePlus
from django.conf.urls.defaults import patterns, include, url
from sitemap import CompanyObjects


sitemaps = {
    'objects': CompanyObjects,
}
admin.site = AdminSitePlus()
admin.autodiscover()


urlpatterns = patterns('',
    (r'^ckeditor/', include('ckeditor.urls')),
    (r'^admin/', include(admin.site.urls)),

    url(r'^order/', include('order.urls', 'order')),
    url(r'^', include('company.urls')),
    url(r'^awards/$', FrontAwards.as_view(), name='awards'),
    url(r'^awards/vote/(?P<type>[0-9A-Za-z-_.//]+)/$', VoteAwards.as_view(), name='awards_vote'),
    url(r'^awards/request/$', RequestForm.as_view(), name='awards_request'),
    url(r'^awards/request/success/$', SuccessRequest.as_view(), name='awards_success'),
    url(r'^awards/add/vote/$', AddVote.as_view(), name='awards_add_vote'),
    url(r'^tender/$', TenderAdd.as_view(), name='tender'),

    url(r'^like/add/(?P<pk>\d+)/$', AddLike.as_view(), name="add_like"),
    url(r'^news/$', NewsList.as_view(), name='news_list'),
    url(r'^news/comment/$', AddComment.as_view(), name='add_comment'),
    url(r'^news/(?P<pk>[0-9A-Za-z-_.//]+)/$', NewsView.as_view(), name='news'),
    url(r'^articles/$', ArticleList.as_view(), name='article_list'),
    url(r'^articles/(?P<pk>[0-9A-Za-z-_.//]+)/$', ArticleView.as_view(), name='article'),
    # url(r'^category/(?P<pk>[0-9A-Za-z-_.//]+)/', CategoryView.as_view(template_name='category.html')),
    # url('^api/buy/product/$', CartAddItemView.as_view(action='post'), name='add_to_cart' ),
    # url(r'^shop/cart/$', CartView.as_view(), name='cart'),
    # url(r'^shop/checkout/$', CheckoutView.as_view(template_name='checkout.html'), name='checkout_selection'),

    # (r'^shop/', include(shop_urls)),
    (r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}),
# (r'^accounts/logout/$', RedirectView.as_view(url='/')),
    url(r'^accounts/', include('registration.urls')),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^robots.txt', include('robots.urls')),
    url(r'^chaining/', include('smart_selects.urls')),
    url(r'', include('comments.urls')),
    url(r'^landging/', include('cms_page.urls')),
    (r'^sitemap.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
    # (r'^sitemap/$', 'django.contrib.sitemaps.views.sitemap', {
    #     'sitemaps': {'cmspages': CMSSitemap},
    #     'mimetype': 'text/html',
    #     'template_name': 'inclusion/site_map.html'
    #     }),
    url(r'^', include('cms.urls')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/news/models.py
# vim:fileencoding=utf-8
from django.db.models import permalink
import os
import uuid
import settings
from sorl.thumbnail.fields import ImageField
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.


def get_file_path(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s.%s" % (uuid.uuid4(), ext)
    return os.path.join(getattr(settings, 'PRODUCT_IMAGE_UPLOAD_TO', 'news/'), filename)


class News(models.Model):
    class Meta(object):
        verbose_name = u'Новость'
        verbose_name_plural = u'Новости'
        ordering = ['-date']

    title = models.CharField(max_length=255, verbose_name=u'Заголовок')
    date = models.DateTimeField(max_length=255, verbose_name=u'Дата публикации')
    image = ImageField(verbose_name=u'Изображение', upload_to=get_file_path, null=True, blank=True)
    teaser = models.TextField(verbose_name=u'Анонс', blank=True, null=True)
    content = RichTextField(verbose_name=u'Текст')
    category = models.ManyToManyField('Category', verbose_name=u'Категории новости',blank=True, null=True)
    keywords = models.TextField(verbose_name=u'Мета Keywords', blank=True, null=True)
    description = models.TextField(verbose_name=u'Meta Description', blank=True, null=True)
    seo_title = models.CharField(max_length=255, verbose_name=u'Seo тайтл', blank=True, null=True,)
    comments_count = models.PositiveIntegerField(u'Количество комментариев', default=0)

    def __unicode__(self):
        return self.title

    @permalink
    def get_absolute_url(self):
        return 'news', (self.id, ), {}


class Category(models.Model):
    class Meta(object):
        verbose_name = u'Категория'
        verbose_name_plural = u'Категории'
        ordering = ['name']

    name = models.CharField(max_length=255, verbose_name=u'Название')

    def __unicode__(self):
        return self.name


class Comment(models.Model):
    class Meta(object):
        verbose_name = u'Комментарий'
        verbose_name_plural = u'Комментарии'
        ordering = ['-created']

    news = models.ForeignKey(News, verbose_name=u'Новость', related_name='comments')
    created = models.DateTimeField(auto_now_add=True, verbose_name=u'Дата', null=True, blank=True)
    name = models.CharField(max_length=255, verbose_name=u'Имя')
    email = models.EmailField(max_length=255, verbose_name=u'E-mail')
    text = RichTextField(verbose_name=u'Текст отзыва', config_name='respond', max_length=2500)
    moderate = models.BooleanField(verbose_name=u'Модерация', default=False)

    def __unicode__(self):
        return "%s - %s" % (self.name, self.email)

apps/news/forms.py
from captcha.fields import CaptchaField
from django.forms.models import ModelForm
from django import forms
from news.models import Comment

__author__ = 'Ivan'


class AddCommentForm(ModelForm):
    class Meta(object):
        model = Comment
        exclude = ['created', 'moderate']

    captcha = CaptchaField()

apps/news/views.py
# vim:fileencoding=utf-8
from django.contrib import messages
from django.shortcuts import get_object_or_404
from django.views.generic.edit import CreateView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from news.forms import AddCommentForm
from news.models import News, Comment
from django.contrib.messages.constants import ERROR, INFO
from apps.articles.models import Article


class NewsList(ListView):
    template_name = "news/news_list.html"
    paginate_by = 10
    model = News
    context_object_name = 'list'

    def get_context_data(self, **kwargs):
        ctx = super(NewsList, self).get_context_data(**kwargs)
        ctx['articles'] = Article.objects.all()[:7]
        # News.objects.all()
        # from news.models import News
        return ctx

    def get_queryset(self):
        tag = self.request.GET.get('tag', False)
        if tag:
            queryset = self.model.objects.filter(category__name=tag)
        else:
            queryset = self.model.objects.all()
        return queryset


class NewsView(DetailView):
    model = News
    template_name = 'news/news.html'
    context_object_name = 'news'

    def get_context_data(self, **kwargs):
        ctx = super(NewsView, self).get_context_data(**kwargs)
        ctx['form'] = AddCommentForm(initial={'news': ctx['object'].id})
        return ctx


class AddComment(CreateView):
    model = Comment
    form_class = AddCommentForm
    template_name = 'news/add_comment.html'

    def get_success_url(self):
        news_id = self.request.POST.get('news', False)
        if news_id:
            url = get_object_or_404(News, id=news_id).get_absolute_url()
        else:
            url = '/'
        messages.add_message(self.request, INFO, u'Комментарий добавлен, в ближайшее время он будет рассмотрен администрацией сайта')
        return url

templates/news/add_comment.html
{% extends "base.html" %}
{% load thumbnail %}


{% block title %}Добавить комментарий{% endblock %}
{% block og_title %}Добавить комментарий{% endblock %}

{% block content %}
    <span class="back">
        <a href="/">Вернуться назад</a>
    </span>

    <h1>Добавить комментарий</h1>



    <form action="." method="POST">
    {% csrf_token %}
    <div class="dobavka" style="margin-bottom: 20px;">

        <div class="pole">
            <label for="id_name">Введите имя</label>
            {{ form.name }}
            {{ form.name.errors }}
        </div>

        <div class="pole">
            <label for="id_email">Введите E-mail</label>
            {{ form.email }}
            {{ form.email.errors }}
        </div>


        <div class="pole txt">
            <label for="txt"> Текст комментария </label>


            <div class="clr"></div>
            {{ form.text }}
            {{ form.text.errors }}
        </div>

        <div class="niz">
            <div class="captcha">
                <em>Введите символы, изображенные на картинке:</em>
                {{ form.captcha }}
                {{ form.captcha.errors }}

            </div>

            <div class="hidden" style="display: none;">
                {% for hidden in form.hidden_fields %}
                    {{ hidden }}
                {% endfor %}
            </div>

            <div class="pole" style="display: none;">
                {{ form.news }}
                {{ form.news.errors }}
            </div>

            <button class="dobavit f-size">Добавить комментарий</button>
        </div>

        <div class="clr"></div>


    </div>
    </form>

    <script type="text/javascript">
        $(function(){
            CKEDITOR.instances.id_text.on('key', checkLength);
            CKEDITOR.instances.id_text.on('paste', checkLength);
        });
    </script>


{% endblock %}

templates/news/news.html
{% extends "base.html" %}
{% load thumbnail %}
{% load encode_parameters %}
{% load comments_tags %}
{% load static %}
{% load widget_tweaks %}

{% block title %}{% if news.seo_title %}{{ news.seo_title }}{% else %}{{ news.title }}{% endif %}{% endblock %}
{% block og_title %}{% if news.seo_title %}{{ news.seo_title }}{% else %}{{ news.title }}{% endif %}{% endblock %}
{% block keywords %}{{ news.keywords }}{% endblock %}
{% block description %}{{ news.description }}{% endblock %}

{% block content %}
    <div class="header header-left-title">
        {% include 'registration/account.html' %}
        <div class="container-sm">
            <h1> &nbsp;{% comment %}{% if 'articles' in request.get_full_path %}Статьи{% else %}Новости{% endif %}{% endcomment %}</h1>
        </div>
    </div>

    <div class="news_content clearfix">
        {% left_nav %}
        <div class="news_detail">
            <div class="news_text article">
                {#                {% thumbnail news.image "170x140" crop="center" as img %}#}
                {#                    <img src="{{ img.url }}" width="{{ img.width }}" height="{{ img.width }}" alt="{{ news.title }}">#}
                {#                {% endthumbnail %}#}
                <img src="{{ news.image.url }}"  alt="{{ news.title }}">
                <h1>{{ news.title }}</h1>
                {{ news.content|safe }}
            </div>

            <div class="news_comments">
                {% render_form_news news %}
                {% render_comments_list_news news %}
                {#                {% for respond in news.comments.all %}#}
                {#                    <div class="comment-info news-comm">#}
                {#                        <img src="{% static "new_img/no_avatar.png" %}">#}
                {#                        <div class="comment">#}
                {#                            <a href="" class="commenter">Александр Поспелов</a>#}
                {#                            <div class="comment-text">{{ respond.text|safe }}</div>#}
                {#                            <div class="com-inf">#}
                {#                                <span class="com-date">({{ respond.created|date:"d m y" }} г.)</span>#}
                {#                                <span class="devider-min">|</span>#}
                {#                                <a href="" class="reply">Ответить</a>#}
                {#                                <span class="devider-min">|</span>#}
                {#                                <a href="" class="like">ЛАЙК: 15 <i></i> </a>#}
                {#                            </div>#}
                {#                        </div>#}
                {#                    </div>#}
                {#                {% endfor %}#}
            </div>
        </div>
    </div>
    {% if user.is_authenticated and user.is_carrier %}
        <script type="text/template" id="template_not_custumer" data-user="{{ user }}">
            <div class="alert-text fix-modal">
                Сейчас вы авторизованы в качестве курьерской или транспортной компании.
                <br/><br/>
                Для того, чтобы оформить заказ на доставку/перевозку вам необходимо
                <a href="{% url auth_logout %}" class="err-link">выйти</a> из личного кабинета и
                <a class="log" href="{% url django.contrib.auth.views.login %}">авторизоваться</a> или
                <a href="{% url registration_choice %}">зарегистрироваться </a> в качестве заказчика.
            </div>
        </script>
        <script>
            $(function () {
                $("a[href*='order/form/']").click(function (e) {
                    e.preventDefault();
                    $.fn.alert({
                        'text': $('#template_not_custumer').html()
                    });
                });
            })
        </script>
    {% endif %}

{% endblock %}

templates/news/news_block.html
<div class="block">
    <div class="name other">
        Новости
    </div>
    <ul class="otzyv">
        {% for news in news_block %}
        <li>
            <span class="zagolovok">
                <a href="{{ news.get_absolute_url }}">{{ news.title|truncatewords:4 }}</a>
                <em>{{ news.date|date:"d M." }}</em>
            </span>
            <div class="clr"></div>
            <div class="tekst">
                {{ news.teaser|truncatewords:14 }}
            </div>
        </li>
        {% endfor %}
    </ul>
    <span class="polnyi"><a href="{% url news_list %}">все новости</a></span>
</div>

templates/news/news_list.html
{% extends "base.html" %}
{% load thumbnail %}
{% load encode_parameters %}
{% load static %}
{% load company %}
{% block content %}
    <div class="header header-left-title">
        {% include 'registration/account.html' %}
        <div class="container-sm">
            <h1>{% if 'articles' in request.get_full_path %}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Статьи{% else %}Новости рынка{% endif %}</h1>
        </div>
    </div>
    <div class="news_content clearfix">
    {% left_nav %}
        <div class="news_list">
            <div class="inner">
                {% for news in list %}
                    <div class="news_item">
                        <a href="{{ news.get_absolute_url }}" class="item_img">
                        {% if news.image %}
                            {% thumbnail news.image "240x160" crop="center" as img %}
                                <img src="{{ img.url }}" width="{{ img.width }}" height="{{ img.height }}" alt="{{ news.title }}"></a>
                            {% endthumbnail %}
                        {% endif %}
                        <div class="item_desc">
                            <div class="info">
                                <img src="{% static "new_img/calendar.png" %}" alt=""><span>{{ news.date|date:"d.m.y" }}</span>
                                <img src="{% static "new_img/comments.png" %}" alt=""><span>{{ news.comments_count }}</span>
                            </div>
                            <header><a href="{{ news.get_absolute_url }}">{{ news.title }}</a></header>
                            <p>{{ news.teaser }}</p>
                        </div>
                    </div>
                {% endfor %}
                {% paginator2 %}
            </div>
        </div>
    </div>

{% endblock %}
