apps/comments/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('',
    url(r'comments/new/$', 'comments.views.comments_add', name='comments_add'),
)

apps/order/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from order.views import OrderCategoryList, OrderFormView, OrderListView, \
    OrderDetailView, OrderBetAddView, OrderBetSetStatusView,     OrderBetConfirmationView, OrderCancelView, \
    OrderCloseView, CityAutocompleteView, SignIn, ListNotificationRoute, AddNotificationRoute, EditNotificationRoute, \
    DeleteNotificationRoute, OrderFormUpdateView, SuccessOrder, Unsubscribe

urlpatterns = patterns('',
    url(r'^detail/(?P<pk>\d+)/$', OrderDetailView.as_view(), name='order_detail'),
    url(r'^list/category/$', OrderCategoryList.as_view(), name='order_category_list'),
    url(r'^form/(?P<category_pk>\d+)/$', OrderFormView.as_view(),
        name='order_form'),
    url(r'^form/(?P<pk>\d+)/edit/$', OrderFormUpdateView.as_view(),
        name='order_update_form'),
    url(r'^list/$', OrderListView.as_view(), name='order_list'),
    url(r'^(?P<pk>\d+)/bet/add/$', OrderBetAddView.as_view(),
        name='order_bet_add'),
    url(r'^bet/(?P<pk>\d+)/(?P<status>[1|2])/$', OrderBetSetStatusView.as_view(),
        name='order_bet_set_status'),
    url(r'^(?P<pk>\d+)/confirmation/(?P<action>yes|cancel)/$',
        OrderBetConfirmationView.as_view(), name='order_confirmation'),
    url(r'^cancel/(?P<match>.+)/$', OrderCancelView.as_view(),
        name='order_cancel'),
    url(r'^order/(?P<pk>\d+)/close/(?P<status>[2|3])/$', OrderCloseView.as_view(),
        name='order_close'),
    url(r'^city/autocomplete/$', CityAutocompleteView.as_view(), name='city_autocomplete'),
    url(r'^login/$', SignIn.as_view(), name='login'),
    url(r'^route/list/$', ListNotificationRoute.as_view(), name='route_list'),
    url(r'^route/add/$', AddNotificationRoute.as_view(), name='add_route'),
    url(r'^route/edit/(?P<pk>\d+)/$', EditNotificationRoute.as_view(), name='edit_route'),
    url(r'^route/delete/(?P<pk>\d+)/$', DeleteNotificationRoute.as_view(), name='delete_route'),

    url(r'^form/(?P<category_pk>\d+)/success/$', SuccessOrder.as_view(), name='add_success'),
    url(r'^unsubscribe/(?P<uuid>[0-9A-Za-z-_.//]+)/$', Unsubscribe.as_view(), name='unsubscribe'),
)

urls.py
# Uncomment the next two lines to enable the admin:
from articles.views import ArticleList, ArticleView
from company.views import counter, RegisterView, CompanyView, CompanyList, \
    AddRespond, FrontView, StatView, TenderAdd, \
    RespondList, OfferView, EditProfile, Avatar, \
    OrdersSend, CompanyScript, DeliveryZonePriceView, \
    CompetitionView, CompetitionDetailView, \
    CompetitionListView
from company.ajax import poll_post, vote
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.views.generic.base import RedirectView
from cms.sitemaps import CMSSitemap

from news.views import NewsList, NewsView, AddComment
from apps.comments.views import AddLike

from awards.views import FrontAwards, VoteAwards, AddVote,\
                         RequestForm, SuccessRequest
import settings

from adminplus.sites import AdminSitePlus
from django.conf.urls.defaults import patterns, include, url
from sitemap import CompanyObjects


sitemaps = {
    'objects': CompanyObjects,
}
admin.site = AdminSitePlus()
admin.autodiscover()


urlpatterns = patterns('',
    (r'^ckeditor/', include('ckeditor.urls')),
    (r'^admin/', include(admin.site.urls)),

    url(r'^order/', include('order.urls', 'order')),
    url(r'^', include('company.urls')),
    url(r'^awards/$', FrontAwards.as_view(), name='awards'),
    url(r'^awards/vote/(?P<type>[0-9A-Za-z-_.//]+)/$', VoteAwards.as_view(), name='awards_vote'),
    url(r'^awards/request/$', RequestForm.as_view(), name='awards_request'),
    url(r'^awards/request/success/$', SuccessRequest.as_view(), name='awards_success'),
    url(r'^awards/add/vote/$', AddVote.as_view(), name='awards_add_vote'),
    url(r'^tender/$', TenderAdd.as_view(), name='tender'),

    url(r'^like/add/(?P<pk>\d+)/$', AddLike.as_view(), name="add_like"),
    url(r'^news/$', NewsList.as_view(), name='news_list'),
    url(r'^news/comment/$', AddComment.as_view(), name='add_comment'),
    url(r'^news/(?P<pk>[0-9A-Za-z-_.//]+)/$', NewsView.as_view(), name='news'),
    url(r'^articles/$', ArticleList.as_view(), name='article_list'),
    url(r'^articles/(?P<pk>[0-9A-Za-z-_.//]+)/$', ArticleView.as_view(), name='article'),
    # url(r'^category/(?P<pk>[0-9A-Za-z-_.//]+)/', CategoryView.as_view(template_name='category.html')),
    # url('^api/buy/product/$', CartAddItemView.as_view(action='post'), name='add_to_cart' ),
    # url(r'^shop/cart/$', CartView.as_view(), name='cart'),
    # url(r'^shop/checkout/$', CheckoutView.as_view(template_name='checkout.html'), name='checkout_selection'),

    # (r'^shop/', include(shop_urls)),
    (r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}),
# (r'^accounts/logout/$', RedirectView.as_view(url='/')),
    url(r'^accounts/', include('registration.urls')),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^robots.txt', include('robots.urls')),
    url(r'^chaining/', include('smart_selects.urls')),
    url(r'', include('comments.urls')),
    url(r'^landging/', include('cms_page.urls')),
    (r'^sitemap.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
    # (r'^sitemap/$', 'django.contrib.sitemaps.views.sitemap', {
    #     'sitemaps': {'cmspages': CMSSitemap},
    #     'mimetype': 'text/html',
    #     'template_name': 'inclusion/site_map.html'
    #     }),
    url(r'^', include('cms.urls')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/order/models.py
#coding: utf-8
from django.core.exceptions import ObjectDoesNotExist
from django.core.urlresolvers import reverse_lazy
from django.db import models
from django.utils.translation import ugettext_lazy as _
from ckeditor.fields import RichTextField
from django.utils import timezone
from dateutil import tz
from decimal import Decimal
from django.contrib.auth.models import User
import json

from smart_selects.db_fields import ChainedForeignKey


LOADERS_CHOICES = (
    (1, _(u'Погрузка разгрузка не требуется')),
    (2, _(u'Достаточно помощи водителя при погрузке')),
    (3, _(u'Требуется 1 грузчик для погрузки')),
    (4, _(u'Требуется 2 грузчика для погрузки')),
    (5, _(u'Требуется 3 грузчика для погрузки')),
    (6, _(u'Требуется 4 грузчика для погрузки')),
)


ROUTE_KIND = (
    (1, _(u'Регион')),
    (2, _(u'Маршрут')),
)


SERVICE = (
    (1, _(u'Перевозка/доставка')),
    (2, _(u'Перевозка + грузчик')),
    (3, _(u'Первозка + 2 грузчика')),
    (4, _(u'Первозка + 3 грузчика')),
    (5, _(u'Первозка + 4 грузчика')),
)

CURRENCY = (
    (1, u'руб.'),
    (2, u'грн.'),
    (3, u'блр.'),
    (4, u'кзт.'),
)

TRANSPORTATION_TYPE = (
    (1, _(u'Купить и привезти')),
    (2, _(u'Нужна только перевозка'))
)

TRANSPORTATION_TYPE_BET = (
    (1, _(u'Отдельная машина')),
    (2, _(u'Сборный груз (догруз)'))
)

ADDRESS_TYPE = (
    (1, _(u'Начальный пункт')),
    (2, _(u'Конечный пункт'))
)

ORDER_BET_STATUS = (
    (0, _(u'Ждет подтверждения')),
    (1, _(u'Ставка принята')),
    (2, _(u'Ставка отклонена')),
)

ORDER_BET_REJECT_KIND_CUSTOMER = (
    (1, _(u'Не устраивает сумма перевозки')),
    (2, _(u'Не устраивает дата/время перевозки')),
)

ORDER_BET_REJECT_KIND = (
    (0, _(u'Отклонена заказчиком')),) +\
    ORDER_BET_REJECT_KIND_CUSTOMER + (
    (11, _(u'Обновлена')),
    (12, _(u'Отклонена перевозчиком')),
)


ORDER_STATUS = (
    (0, _(u'Идут торги')),
    # (5, _(u'Подтверждение перевозчиком')),
    (5, _(u'Ожидает подтверждения')),
    (1, _(u'Выполняется')),
    (2, _(u'Завершен')),
    (3, _(u'Не выполнен')),
    (4, _(u'Отменен')),
    (6, _(u'Не актуален')),
)

MODALITIES = (
    (1, _(u'Фургон')),
    (2, _(u'Эвакуатор')),
    (3, _(u'Ж/д транспорт')),
    (4, _(u'Автоваз')),
    (5, _(u'Своим ходом')),
    (6, _(u'Буксировка')),
)

REVIEW_KIND = (
    (1, _(u'Положительный')),
    (2, _(u'Отрицательный')),
    (3, _(u'Нейтральный')),
)


class Profile(models.Model):
    user = models.OneToOneField(User)
    phone = models.CharField(max_length=255, blank=True, null=True, verbose_name='phone')

    class Meta:
        ordering = ['user']
        verbose_name = 'user'
        verbose_name_plural = 'users'


class OrderCategory(models.Model):
    name = models.CharField(_(u'Название'), max_length=120)
    icon = models.ImageField(
        _(u'Иконка'), upload_to='order_category/icon', null=True, blank=True)
    icon_white = models.ImageField(
        _(u'Белая иконка'), upload_to='order_category/icon_white', null=True, blank=True)
    ordering = models.IntegerField(_(u'Порядок вывода'), default=1)
    block_width = models.IntegerField(
        _(u'Ширина блока'), default=1,
        help_text=_(u'От 1 до 4. Имееться введу ширина блока в плитке'
                    u' на главной странице'))
    name_description = models.CharField(
        _(u'Описание загаловка'), blank=True, null=True,
        max_length=255, help_text=_(u'Выводиться при оформлении заказа в поле'
                                    u' заголовка в качестве placeholder'))
    name_example = RichTextField(
        _(u'Пример заговловка'), blank=True, null=True,
        max_length=255, help_text=_(u'Выводиться при оформлении заказа в поле '
                                    u'заголовка при наведении на поле'))
    name_options = models.CharField(
        _(u'Варианты заголовка'), blank=True, null=True,
        max_length=255, help_text=_(u'Через запятую. Выводиться в при '
                                    u'оформлении заказа ниже поля заголовка'))
    name_options_erase = models.BooleanField(
        _(u'Очищать поле заголовка при выборе нового варианта'),
        default=False
    )
    body_description = models.TextField(
        _(u'Описание доп. информации'), blank=True, null=True,
        help_text=_(u'Выводиться при оформлении заказа в поле '
                    u'доп. информации в качестве placeholder'))
    body_example = RichTextField(
        _(u'Пример доп. информации'), blank=True, null=True,
        help_text=_(u'Выводиться при оформлении заказа в поле '
                    u'доп. информации при наведении на поле'))
    body_options = models.CharField(
        _(u'Варианты доп. информации'), blank=True, null=True, max_length=255,
        help_text=_(u'Через запятую. Выводиться в при оформлении заказа '
                    u'ниже поля доп. информации'))
    cargo_weight = models.BooleanField(
        _(u'Вес груза'), default=False,
        help_text=_(u'Показывать поле "вес груза" при оформлении заказа'))
    cargo_volume = models.BooleanField(
        _(u'Объем груза'), default=False,
        help_text=_(u'Показывать поле "объем груза" при оформлении заказа'))
    loaders = models.BooleanField(
        _(u'Грузчики'), default=False,
        help_text=_(u'Показывать поле "грузчики" при оформлении заказа'))
    can_be_distilled = models.BooleanField(
        _(u'Можно перегнать'), default=False,
        help_text=_(u'Показывать поле "можно перегнать" при оформлении заказа'))
    not_on_move = models.BooleanField(
        _(u'Не на ходу'), default=False,
        help_text=_(u'Показывать поле "не на ходу" при оформлении заказа'))
    transportation_type = models.BooleanField(
        _(u'Только перевезти или перевезти и купить'), default=False,
        help_text=_(u'Показывать поле "Только перевезти или перевезти и купить" '
                    u'при оформлении заказа'))
    services = models.ManyToManyField(
        'OrderService', verbose_name=_(u'Услуги перевозчика'),
        null=True, blank=True)
    count_items = models.BooleanField(
        _(u'Множественное количество обьектов перевозки'), default=False,
        help_text=_(u'Возможность добавить дополнительное поле для обьекта перевозки.'))
    carriage_passengers = models.BooleanField(
        _(u'Перевозка пасажиров'), default=False,
        help_text=_(u'Показывать поле перевозки пасажиров'))
    modalities = models.BooleanField(
        _(u'Доступные споособы перевозок'), default=False,
        help_text=_(u'Показывать поле "Доступные споособы перевозок" '
                    u'при оформлении заказа'))
    transportation_type_in_bet = models.BooleanField(
        _(u'Тип перевозки при оформлении ставки'), default=False,
        help_text=_(u'Показывать выбор типа перевозки(Отдельная машина/Сборный '
                    u'груз(догруз)) при оформлении ставки'))
    modalities_bet = models.BooleanField(
        _(u'Тип перевозки'), default=False,
        help_text=_(u'Показывать поле "Тип перевозки" '
                    u'при отклике на заказ'))

    def get_fields(self):

        fields_list = ['cargo_weight', 'cargo_volume', 'loaders',
                       'can_be_distilled', 'not_on_move', 'body_description',
                       'buy_and_transportation', 'only_transportation']
        fields = dict()
        for field in fields_list:
            fields[field] = getattr(self, field, False)
        return fields

    def __unicode__(self):
        return unicode(self.name)

    class Meta:
        verbose_name = _(u'Категория заказа')
        verbose_name_plural = _(u'Категории заказа')
        ordering = ('ordering',)


class OrderService(models.Model):
    name = models.CharField(_(u'Название'), max_length=120)
    icon = models.ImageField(
        _(u'Иконка'), upload_to='order_service/icon', null=True, blank=True)
    description = models.TextField(_(u'Описание'), null=True, blank=True)
    ordering = models.IntegerField(_(u'Порядок вывода'), default=1)

    class Meta:
        verbose_name = _(u'Услуга перевозчика')
        verbose_name_plural = _(u'Услуги перевозчика')
        ordering = ('ordering',)

    def __unicode__(self):
        return unicode(self.name)


class OrderAddress(models.Model):
    country = models.ForeignKey(
        'geo.Country', verbose_name=_(u'Страна'), null=True, blank=True)
    region = ChainedForeignKey(
        'geo.Region', verbose_name=_(u'Область'), null=True, blank=True,
        chained_field='country', chained_model_field='country', auto_choose=True)
    city = ChainedForeignKey(
        'geo.City', verbose_name=_(u'Город'), null=True, blank=True,
        chained_field='region', chained_model_field='region', auto_choose=True)
    order = models.ForeignKey(
        'order.Order', related_name='addresses', verbose_name=_(u'Заказ'))
    long_position = models.DecimalField(max_digits=16, decimal_places=8,
                                        default=Decimal('0.00'))
    lat_position = models.DecimalField(max_digits=16, decimal_places=8,
                                       default=Decimal('0.00'))
    type = models.SmallIntegerField(
        _(u'Тип пункта'), choices=ADDRESS_TYPE, default=1)
    address = models.CharField(
        _(u'Улица, дом'), max_length=255, blank=True)

    # def __unicode__(self):
    #     return '%s-%s' % (self.country.name, self.region.name)


class OrderName(models.Model):
    name = models.CharField(_(u'Заголовок'), max_length=255)
    count = models.PositiveIntegerField(_(u'Количество'), default=1)
    order = models.ForeignKey('Order', related_name='order_name')


class OrderManager(models.Manager):
    def get_count_new_bet(self, user):
        """ Возращаем количество новых ставок к заказу """
        return self.filter(bets__is_read=False, user__id=user.id).count()

    def get_auto_selected(self):
        return self.filter(auto_selected=True)


class Order(models.Model):
    user = models.ForeignKey(
        User, related_name='orders',
        verbose_name=_(u'Заказчик'))

templates/order/add_success.html
{% extends "base.html" %}

{% block title %}Ваш заказ успешно добавлен на сайт.{% endblock %}
{% block title_content %}Ваш заказ успешно добавлен на сайт.{% endblock %}


{% block right_content %}
    <h2>Ваш заказ успешно добавлен на сайт.</h2>
    <br/>
    <p>Компании, которые занимаются перевозкой/доставкой соответствующих категорий, получили уведомление о вашем заказе.
        <br/>Теперь просто ждите предложений по цене, из которых выберите для себя оптимальное.</p>
    <a href="/" class="link next" >Перейти к вашему заказу</a>
    <script>
        $(function () {
            if ($.fn.getParameterByName('next')) {
{#                $.fn.alert({#}
{#                    title: 'Заказ',#}
{#                    text: 'Ваш заказ успешно добавлен на сайт'#}
{#                });#}
                $('.next').attr('href', $.fn.getParameterByName('next'));
                window.history.replaceState(null, null, location.protocol + '//' + location.host + location.pathname)
            }
        });
    </script>
{% endblock %}

templates/order/not_found.html
{% extends "base.html" %}


{% block title %}Заказа с таким номером не существует.{% endblock %}
{% block title_content %}Заказа с таким номером не существует.{% endblock %}
{% block og_title %}Заказа с таким номером не существует.{% endblock %}

{% block right_content %}
    <h2>Заказа с таким номером не существует.</h2>
    <br/>
    <a class='link' href="{% url order:order_list  %}">К списку</a>
{% endblock %}

templates/order/order_category_list.html
{% load thumbnail %}

<div id="modal-list-categories" class="step-0">
    <div class="top-type"><span>Выбор категории</span></div>
    <div class="close" onclick="order.close_dialog()"></div>
    <div class="wrap-container">
        <div class="container">
            <span class="title">Выберите категорию груза:</span>
            <div class="wrap-category font-res">
                {% for category in categories %}
                    <a class="category" href='javascript:void(0)' data-url="{% url order:order_form category.id %}"
                       onclick="order.open_dialog(this, {height: 478, width: 925, step:1}); return false;">
                        <div class="round">
                            <img src="{{ category.icon.url }}" alt="" style="margin: {{ category.icon|margin:'79x79' }}" />
                        </div>
                        <span {% if category.id == 7 %}style="font-size: 0.85em;"{% endif %}>{{ category.name }}</span>
                    </a>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

templates/order/order_form.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% load order_tags %}
{% load company %}
{% block title %}Оформление заказа{% endblock %}
{% block js %}
    <script src="//api-maps.yandex.ru/2.0/?load=package.standard,package.route&lang=ru-RU" type="text/javascript"></script>
    <script type="text/javascript" src="{% static "order/js/map2.js" %}"></script>
{% endblock %}
{% block content %}
    <div class="header header-ordering">
        {% include 'registration/account.html' %}
        <div class="container-sm">
            <h3>Оформление заказа</h3>
        </div>
    </div>

    <div class="ordering_content">
        <div class="container-sm">
            <div class="order_category clearfix">
                <div class="category_logo">
                    <img src="{{ order_category.icon.url }}" alt="">
                </div>
                <h3>{{ order_category.name }}</h3>
                {% if 'edit' not in request.get_full_path %}
                    <a href="#" class="order_modal">изменить категорию</a>
                {% endif %}
            </div>

            <form action="." method="post" class="ordering_form clearfix">
                {% csrf_token %}
                <div class="ordering_map">
                    <div class='map' id="map"></div>
                    <a href="#" id="search-address"><span>Проложить маршрут</span><img src="{% static "new_img/map_marker.png" %}" alt=""></a>
                </div>
                <fieldset>
                    <legend><span>1</span>Нужно перевезти / доставить:</legend>
                    <div class="form_group type">
                        {% render_field form.name placeholder=order_category.name_description title=order_category.name_example|safe required='true' %}
                        {#                        <p class="error">Обазательно к заполнению</p>#}
                        {% for option in order_category.name_options|split:"," %}
                            <a href="#">{{ option }}</a>
                        {% endfor %}
                    </div>

                    <div class="form_group">
                        {% render_field form.body placeholder=order_category.body_description title=order_category.body_example %}
                        <div class="error {{ form.body.name }}"></div>
                    </div>
                    {% if form.cargo_weight or form.cargo_volume or form.loaders %}
                        <div class="form_group group">
                            {% if form.cargo_weight %}
                                {% render_field form.cargo_weight placeholder="Вес груза" class=form.cargo_weight|error title="Вес груза" %}
                                <span>кг</span>
                            {% endif %}
                            {% if form.cargo_volume %}
                                {% render_field form.cargo_volume placeholder='Обьем груза' class=form.cargo_weight|error title='Обьем груза' %}
                                <div class="sub_rel"><span>м</span><sup>3</sup></div>
                            {% endif %}
                            {% if form.loaders %}
                                <div class="styled-select cus">
                                    {% render_field form.loaders data-placeholder='Выберите услугу' %}
                                </div>
                            {% endif %}
                            <div class="error {{ form.cargo_volume.name }} {{ form.cargo_weight.name }}"></div>
                        </div>
                    {% endif %}
                </fieldset>
                <div class="clearfix"></div>
                <fieldset>
                    <legend><span>2</span>Откуда, куда, когда:</legend>
                    <div class="form_group from">
                        {% render_field form.country_from class='field-step-1' placeholder=form.country_from.label %}
                        {% render_field form.city_from class='field-step-1' placeholder=form.city_from.label %}
                        {% render_field form.address_from placeholder='ул. Иванова, дом 15' %}
                    </div>
                    <div class="form_group to">
                        {% render_field form.country_to class='field-step-1' placeholder=form.country_to.label %}
                        {% render_field form.city_to class='field-step-1' placeholder=form.city_to.label %}
                        {% render_field form.address_to placeholder='ул. Иванова, дом 15' %}
                    </div>
                    <div class="__all__ error"></div>
                    <div class="form_group from_to_info">
                        {% render_field form.date placeholder='Дата перевозки/доставки' title='дд.мм.гггг' class="date-carriage datepicker fs-in" %}
                        {% render_field form.time placeholder="Время" class='time' %}
                        <input type="checkbox" id="unknow_date" class="styled"><label> Гибкое время</label>
                    </div>
                    <div class="error {{ form.date.name }} {{ form.time.name }}"></div>
                </fieldset>

                <fieldset>
                    <legend><span>3</span>Дополнительные параметры</legend>
                    <div class="form_group dop">
                        {% render_field form.topicality placeholder="Ставки принимаются до" class="date-carriage datepicker" %}
                        <em></em>
                        {% render_field form.price_max placeholder='Цена максимум' title=title %}
                        <div class="styled-select currency">
                            <label>
                                {% render_field form.currency class="currency" %}
                            </label>
                        </div>

                        <div class="styled-select payment">
                            <label>
                                {% render_field form.payment data-placeholder='Форма оплаты' %}
                            </label>
                        </div>
                    </div>
                    <div class="error {{ form.topicality.name }} {{ form.price_max.name }} {{ form.currency.name }}"></div>
                </fieldset>

                {% if form.email%}
                    <fieldset>
                        <legend><span>4</span>Контакты <i><img src="{% static "new_img/lock.png" %}" alt="">(контакты будут доступны только выбранному Вами перевозчику)</i></legend>
                        <div class="form_group contacts">
                            {% render_field form.username placeholder="Имя" %}
                            {% render_field form.phone placeholder="Мобильный телефон" %}
                            {% render_field form.email type="email" placeholder="Email" %}
                        </div>
                        <div class="error {{ form.username.name }} {{ form.email.name }} {{ form.phone.name }}"></div>
                    </fieldset>
                {% endif %}

                <div class="btn_group">
                    {% if 'edit' in request.get_full_path %}
                        <button type="submit" class="btn" id="submit_order">Cохранить</button>
                        <button type="button" class="btn btn-sm-red btn-cancel cancel" onclick="document.location='{{ order.get_absolute_url }}' ">Отменить</button>
                    {% else %}
                        <button type="submit" class="btn" id="submit_order">Разместить заказ</button>
                    {% endif %}
                </div>
            </form>
        </div>
    </div>
    {% order_category_modal %}

    <script>
        $(function () {
            $("#id_cargo_weight").keyup(function(e){
                var key = e.which ? e.which : event.keyCode;
                if(key == 110 || key == 188){
                    e.preventDefault();
                    var value = $(this).val();
                    $(this).val(value.replace(",","."));
                }
            });
            $('#id_country_from, #id_country_to').on('keydown', function(event) {
                $(this).val($(this).val().substr(0, 1).toUpperCase() + $(this).val().substr(1).toLowerCase());
            });
            var availableTags = [
                'Россия',
                'Украина',
                'Беларусь',
                'Казахстан'
            ];
            $( "#id_country_from, #id_country_to" ).autocomplete({
                source: availableTags
            });
            add_city_autocomplete("#id_city_from, #id_city_to");
        });
    </script>
{% endblock %}

templates/order/unsubscribe.html
{% extends "base.html" %}
{% block title %}Вы успешно отписались от рассылки{% endblock %}

{% block title_content %}Вы успешно отписались от рассылки{% endblock %}

{% block right_content %}
    <p class="right-text">Нам очень жаль, что вы отписались от нашей рассылки. </p>
    <br/>
    <br/>
    <p class="right-text">Изменить или добавить уведомления вы сможете в своем личном кабинете.</p>
    <br/>
    <br/>
    <a href="/" class="link">На главную</a>
{% endblock %}

templates/order/ymap.html
<!DOCTYPE html>
<html>
<head>
    <title>Примеры. Расчет стоимости доставки</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <script src="//api-maps.yandex.ru/2.0/?load=package.standard,package.route&lang=ru-RU" type="text/javascript"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/jquery1.5.2.min.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}order/js/map2.js"></script>
</head>
<body>
<div class="route">
    <div class="from">
        <input type="text" id="start"/>
    </div>
    <div class="to">
        <input type="text" id="end"/>
    </div>
    <input type="text" id="id_distance"/>
</div>
<a href="#" id="search-address">найти</a>
    <div id="map" style="width:520px; height:350px"></div>
</body>
</html>